"""add ban fields to user

Revision ID: 05a24005277b
Revises: 9fc61f0d3249
Create Date: 2026-02-23 12:32:26.603691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a24005277b'
down_revision: Union[str, Sequence[str], None] = '9fc61f0d3249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ban_reason', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_users_banned_until'), 'users', ['banned_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_banned_until'), table_name='users')
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'banned_until')
    # ### end Alembic commands ###
