"""added recommendation_weights table

Revision ID: 06b632938383
Revises: d5ed496f9dac
Create Date: 2026-03-07 17:59:12.078089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b632938383'
down_revision: Union[str, Sequence[str], None] = 'd5ed496f9dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_weights',
    sa.Column('tag_match_weight', sa.Float(), nullable=False),
    sa.Column('year_proximity_weight', sa.Float(), nullable=False),
    sa.Column('rating_weight', sa.Float(), nullable=False),
    sa.Column('popularity_weight', sa.Float(), nullable=False),
    sa.Column('min_rating_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_weights_id'), 'recommendation_weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_weights_id'), table_name='recommendation_weights')
    op.drop_table('recommendation_weights')
    # ### end Alembic commands ###
