"""Final Senior Architecture

Revision ID: 10b5cecbc2d3
Revises: 
Create Date: 2026-02-13 13:48:28.618207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b5cecbc2d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('banner', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('section', sa.Enum('POPULAR', 'RECENT', 'SERIES', 'MOVIES', 'EARLY_ACCESS', 'COMING_SOON', 'ACTIVE_PACKS', name='animesection'), nullable=False),
    sa.Column('highlight_char', sa.String(length=20), nullable=True),
    sa.Column('accent_color', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animes_created_at'), 'animes', ['created_at'], unique=False)
    op.create_index(op.f('ix_animes_id'), 'animes', ['id'], unique=False)
    op.create_index(op.f('ix_animes_section'), 'animes', ['section'], unique=False)
    op.create_index(op.f('ix_animes_slug'), 'animes', ['slug'], unique=True)
    op.create_index(op.f('ix_animes_title'), 'animes', ['title'], unique=False)
    op.create_index(op.f('ix_animes_year'), 'animes', ['year'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CREATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('anime_tags_association',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'tag_id')
    )
    op.create_table('clips',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('quality', sa.Enum('Q_1080P', 'Q_4K', 'Q_720P', name='videoquality'), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_created_at'), 'clips', ['created_at'], unique=False)
    op.create_index(op.f('ix_clips_id'), 'clips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clips_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_created_at'), table_name='clips')
    op.drop_table('clips')
    op.drop_table('anime_tags_association')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_animes_year'), table_name='animes')
    op.drop_index(op.f('ix_animes_title'), table_name='animes')
    op.drop_index(op.f('ix_animes_slug'), table_name='animes')
    op.drop_index(op.f('ix_animes_section'), table_name='animes')
    op.drop_index(op.f('ix_animes_id'), table_name='animes')
    op.drop_index(op.f('ix_animes_created_at'), table_name='animes')
    op.drop_table('animes')
    # ### end Alembic commands ###
