"""Add Phase 3 Moderation Metrics models

Revision ID: 2c903cf75fd6
Revises: f48d437864fb
Create Date: 2026-02-28 16:20:41.328628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c903cf75fd6'
down_revision: Union[str, Sequence[str], None] = 'f48d437864fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_logs',
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_logs_created_at'), 'security_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_logs_event_type'), 'security_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_logs_user_id'), 'security_logs', ['user_id'], unique=False)
    op.add_column('comments', sa.Column('toxicity_score', sa.Float(), nullable=True))
    op.add_column('comments', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_comments_is_spam'), 'comments', ['is_spam'], unique=False)
    op.create_index(op.f('ix_comments_toxicity_score'), 'comments', ['toxicity_score'], unique=False)
    op.add_column('reports', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'resolved_at')
    op.drop_index(op.f('ix_comments_toxicity_score'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_spam'), table_name='comments')
    op.drop_column('comments', 'is_spam')
    op.drop_column('comments', 'toxicity_score')
    op.drop_index(op.f('ix_security_logs_user_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_event_type'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_created_at'), table_name='security_logs')
    op.drop_table('security_logs')
    # ### end Alembic commands ###
