"""Add season episode and news blog

Revision ID: 2ce93b6161d5
Revises: 10b5cecbc2d3
Create Date: 2026-02-13 16:50:16.384281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce93b6161d5'
down_revision: Union[str, Sequence[str], None] = '10b5cecbc2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('clips', sa.Column('episode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'episode')
    op.drop_column('clips', 'season')
    # ### end Alembic commands ###
