"""add_video_path_thumbnail_path_file_size_to_clips

Revision ID: 34ecec2fe3d2
Revises: 307b32d30f12
Create Date: 2026-02-15 19:28:53.077723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ecec2fe3d2'
down_revision: Union[str, Sequence[str], None] = '307b32d30f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Helper to check if column exists
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = {col['name'] for col in inspector.get_columns('clips')}
    
    # Conditionally add columns only if they don't exist
    if 'video_path' not in existing_columns:
        op.add_column('clips', sa.Column('video_path', sa.String(length=500), nullable=True))
    
    if 'thumbnail_path' not in existing_columns:
        op.add_column('clips', sa.Column('thumbnail_path', sa.String(length=500), nullable=True))
    
    if 'duration' not in existing_columns:
        op.add_column('clips', sa.Column('duration', sa.Integer(), nullable=True))
    
    if 'season' not in existing_columns:
        op.add_column('clips', sa.Column('season', sa.Integer(), nullable=True, server_default='1'))
    
    if 'episode' not in existing_columns:
        op.add_column('clips', sa.Column('episode', sa.Integer(), nullable=True, server_default='1'))
    
    # Make video_id nullable since we support both YouTube and local files
    op.alter_column('clips', 'video_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove added columns
    op.drop_column('clips', 'episode')
    op.drop_column('clips', 'season')
    op.drop_column('clips', 'duration')
    op.drop_column('clips', 'thumbnail_path')
    op.drop_column('clips', 'video_path')
    
    # Revert video_id to not nullable
    op.alter_column('clips', 'video_id', nullable=False)
    # ### end Alembic commands ###
