"""add_timecode_seconds_to_comments

Revision ID: 5390d63d125d
Revises: bc06c3d4cb2f
Create Date: 2026-03-09 22:31:14.979542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5390d63d125d'
down_revision: Union[str, Sequence[str], None] = 'bc06c3d4cb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timecode_seconds', sa.Float(), nullable=True))
    op.create_index(op.f('ix_comments_timecode_seconds'), 'comments', ['timecode_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_timecode_seconds'), table_name='comments')
    op.drop_column('comments', 'timecode_seconds')
    # ### end Alembic commands ###
