"""Add Phase 2 Content Metrics models

Revision ID: 57a3e877f370
Revises: 43f8f75d67ae
Create Date: 2026-02-28 15:56:18.059060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a3e877f370'
down_revision: Union[str, Sequence[str], None] = '43f8f75d67ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
