"""Add details JSON column to AuditLog

Revision ID: 73ac97e01bcf
Revises: be0a70ecaab6
Create Date: 2026-03-04 23:18:33.432464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ac97e01bcf'
down_revision: Union[str, Sequence[str], None] = 'be0a70ecaab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###
