"""Add VideoHeatmap model

Revision ID: 7d583ec3df25
Revises: f296741bfbeb
Create Date: 2026-02-28 17:46:55.079122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d583ec3df25'
down_revision: Union[str, Sequence[str], None] = 'f296741bfbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_heatmaps',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('heatmap_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_heatmaps_anime_id'), 'video_heatmaps', ['anime_id'], unique=False)
    op.create_index(op.f('ix_video_heatmaps_id'), 'video_heatmaps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_heatmaps_id'), table_name='video_heatmaps')
    op.drop_index(op.f('ix_video_heatmaps_anime_id'), table_name='video_heatmaps')
    op.drop_table('video_heatmaps')
    # ### end Alembic commands ###
