"""add daily analytics table

Revision ID: b43db41a89ba
Revises: 2e837fddf935
Create Date: 2026-02-23 13:55:37.778963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43db41a89ba'
down_revision: Union[str, Sequence[str], None] = '2e837fddf935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
