"""add webhooks to settings

Revision ID: cd256a82815c
Revises: 05a24005277b
Create Date: 2026-02-23 12:56:15.246352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd256a82815c'
down_revision: Union[str, Sequence[str], None] = '05a24005277b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('telegram_bot_token', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('telegram_chat_id', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('discord_webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'discord_webhook_url')
    op.drop_column('system_settings', 'telegram_chat_id')
    op.drop_column('system_settings', 'telegram_bot_token')
    # ### end Alembic commands ###
