"""added episode_number and bandwidth_mb to video_playback_sessions

Revision ID: d5ed496f9dac
Revises: 73ac97e01bcf
Create Date: 2026-03-07 17:34:01.153535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ed496f9dac'
down_revision: Union[str, Sequence[str], None] = '73ac97e01bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playback_sessions', sa.Column('episode_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('video_playback_sessions', sa.Column('bandwidth_mb', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_playback_sessions', 'bandwidth_mb')
    op.drop_column('video_playback_sessions', 'episode_number')
    # ### end Alembic commands ###
