"""Add Phase 5 Adblock Tracker

Revision ID: f296741bfbeb
Revises: 452b31fc0a95
Create Date: 2026-02-28 17:16:27.890701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f296741bfbeb'
down_revision: Union[str, Sequence[str], None] = '452b31fc0a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_analytics', sa.Column('adblock_detected_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('daily_analytics', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_analytics', 'unique_visitors',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_analytics', 'unique_visitors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_analytics', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('daily_analytics', 'adblock_detected_count')
    # ### end Alembic commands ###
